import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<ul>
					<li>
						<Link href="/">ホーム</Link>
					</li>
					<li>
						<Link href="form">入力フォーム</Link>
					</li>
				</ul>
				{children}
			</body>
		</html>
	);
}
